version: 2.1
jobs:
  test:
    docker:
      - image: circleci/node:10-browsers
    steps:
      - checkout
      - run:
          name: Install dependencies
          command: yarn
      - run:
          name: Run tests (without Percy)
          command: PERCY_ENABLE=0 yarn test
  percy_test:
    docker:
      - image: circleci/node:12-browsers
    steps:
      - checkout
      - run:
          name: Install dependencies
          command: yarn
      - run:
          name: Run tests with Percy
          command: yarn test
  release:
    docker:
      - image: circleci/node:12
    steps:
      - checkout
      - run: yarn
      - run: npx semantic-release
workflows:
  version: 2.1
  test_and_release:
    jobs:
      - test
      - percy_test
      - release:
          requires:
            - test
            - percy_test
